disabled_rules:
- colon
- comma
- control_statement
- function_body_length
- cyclomatic_complexity
- trailing_whitespace

line_length: 150


opt_in_rules:
- empty_count
- missing_docs
- nesting
- force_try/cast/unwrapping
- weak_delegate


excluded:
- Carthage
- Pods
- ChNJokes/Delegates/AppDelegate.swift
- ChNJokes/Delegates/SceneDelegate.swift
- Source/ExcludedFolder
- Source/ExcludedFile.swift


reporter: xcode
warning_threshold: 30
